
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: windows 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
   
        with:
          feed_list: "https://www.linkedin.com/posts/online-graduates_start-your-coding-journey-with-c-basic-activity-7025765427486072834-Dexm?utm_source=share&utm_medium=member_desktop"
