name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Khadim-swe/github-readme-youtube-cards@main
        with:
          channel_id: UCzNt-VWM8zN_A7wBbXCussw
